FROM node:alpine

ARG BASE_PATH
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_API_URL

ENV BASE_PATH=${BASE_PATH}
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

WORKDIR /home/perplexica

COPY ui /home/perplexica/

RUN yarn install
RUN yarn build

CMD ["yarn", "start"]